import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
      className: 'sidebar-home',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Account & Billing',
      items: [{type: 'autogenerated', dirName: 'account-billing'}],
    },
    {
      type: 'category',
      label: 'Website Builder',
      items: [{type: 'autogenerated', dirName: 'website-builder'}],
    },
    {
      type: 'category',
      label: 'Design & Themes',
      items: [{type: 'autogenerated', dirName: 'design-themes'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },
    {
      type: 'category',
      label: 'Best Practices',
      items: [{type: 'autogenerated', dirName: 'best-practices'}],
    },
  ],
};

export default sidebars;
