import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Content Management',
      items: [{type: 'autogenerated', dirName: 'content-management'}],
    },
    {
      type: 'category',
      label: 'Events',
      items: [{type: 'autogenerated', dirName: 'events'}],
    },
    {
      type: 'category',
      label: 'Sermons',
      items: [{type: 'autogenerated', dirName: 'sermons'}],
    },
    {
      type: 'category',
      label: 'Groups',
      items: [{type: 'autogenerated', dirName: 'groups'}],
    },
    {
      type: 'category',
      label: 'Connect Points',
      items: [{type: 'autogenerated', dirName: 'connect-points'}],
    },
    {
      type: 'category',
      label: 'Page Builder',
      items: [{type: 'autogenerated', dirName: 'page-builder'}],
    },
    {
      type: 'category',
      label: 'Design',
      items: [{type: 'autogenerated', dirName: 'design'}],
    },
    {
      type: 'category',
      label: 'SEO',
      items: [{type: 'autogenerated', dirName: 'seo'}],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },
  ],
};

export default sidebars;
